# Generated by Django 5.0.6 on 2024-07-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_lobbydata_player_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobbydata',
            name='player_list',
        ),
        migrations.AddField(
            model_name='lobbydata',
            name='player_list',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
