# Generated by Django 5.0.6 on 2024-07-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_lobbydata_player_list_lobbydata_player_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lobbydata',
            old_name='date_game',
            new_name='date_game_start',
        ),
        migrations.AddField(
            model_name='lobbydata',
            name='date_game_last',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
