# Generated by Django 5.0.6 on 2024-07-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_date_game_lobbydata_date_game_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitsbuildingscountmla',
            name='current_time',
            field=models.IntegerField(),
        ),
    ]
