# Generated by Django 5.0.6 on 2024-07-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_unitsbuildingscountmla_current_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitsbuildingscountmla',
            name='radar_jamming_station_count',
            field=models.IntegerField(default=0),
        ),
    ]
