# Generated by Django 5.0.6 on 2024-07-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_unitsbuildingscountmla_radar_jamming_station_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playersgameshistory',
            old_name='date_game',
            new_name='date_game_start',
        ),
        migrations.AddField(
            model_name='playersgameshistory',
            name='date_game_last',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
